version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dating_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - minio
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - S3_ENDPOINT=minio:9000
      - ENVIRONMENT=development
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - .:/app
    command: watchmedo auto-restart --directory=. --pattern=*.py --recursive -- python main.py


  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis
      - postgres
      - minio
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - S3_ENDPOINT=minio:9000
    volumes:
      - ./logs:/app/logs
      - .:/app
    command: celery -A celery_app worker --loglevel=info
    restart: unless-stopped

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - S3_ENDPOINT=minio:9000
    volumes:
      - ./logs:/app/logs
      - .:/app
    command: celery -A celery_app beat --loglevel=info
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data: